name: sweet_vpn
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^11.1.2
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.4.0
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/peace_sans.ttf
    - assets/imgs/
  fonts:
    - family: PeaceSans
      fonts:
        - asset: assets/fonts/peace_sans.ttf

flutter_assets:
  assets_path: assets/
  output_path: lib/as/
  filename: assets.dart
